matrix:
  include:
    - language: node_js
      node_js:
        - "8"
      dist: bionic
      cache:
        directories:
          - nodejs/node_modules
      install:
        - curl --silent --show-error https://raw.githubusercontent.com/davidkhala/node-utils/master/scripts/npm.sh | bash -s packageLock false
        - export BIN_Parent=$PWD
        - ./bash/pullBIN.sh
        - cd nodejs; npm install; cd -;
      script:
        - node nodejs/test



