matrix:
  include:
    - language: node_js
      node_js:
        - "8"
      dist: bionic
      cache:
        directories:
          - nodejs/node_modules
      install:
        - ./install.sh travis
        - cd nodejs; npm install; cd -;
      script:
        - node nodejs/test



